#!/bin/bash
psql -a -e --username root -c "CREATE ROLE $MAGPIE_DATABASES_USER WITH LOGIN ENCRYPTED PASSWORD '$MAGPIE_DATABASES_PASSWORD';"
psql -a -e --username root -c "CREATE DATABASE $MAGPIE_DATABASES_NAME OWNER =  $MAGPIE_DATABASES_USER;"
psql -a -e --username root -c "ALTER USER $MAGPIE_DATABASES_USER CREATEDB;"